theme = "hook"
generate_feeds = true

# The URL the site will be built for
base_url = "/gists"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

title = "Anosora233"
description = "Github user anosora233's gists"

taxonomies = [
    # { name = "categories" },
    { name = "tags" },
]

[markdown]

bottom_footnotes = true

[markdown.highlighting]

dark_theme = "min-dark"
light_theme = "min-light"

[extra]
# Put all your custom variables here

links = [
    { title = "Mail", href = "mailto:feixiangs@outlook.com" },
    { title = "GitHub", href = "https://github.com/anosora233" },
    # { title = "LinkedIn", href = "https://linkedin.com" }
]
